{{- if .Values.serviceReplica.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-replica
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceReplica.type }}
  ports:
    - port: {{ .Values.serviceReplica.externalPort }}
      targetPort: {{ .Values.serviceReplica.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- end }}
